### ISSUE TITLE
Modifying code for custom stratification ratio

### ISSUE THREAD

**Issue by mhashas** [galatolofederico/pytorch-balanced-batch#2]
Hi

First of all thanks for this repository, it's definitely useful. I was wondering if you have any tips on how to modify the code to have a custom stratification ratio, i.e. instead of balanced have twice as many class 1 than class 0. I have been playing a bit with the code but to no success so far.

**Comment by galatolofederico** [comment]
Hi, I didn't expect that such small code can be this useful. 
It is an interesting idea. I think that the code needs a bit of refactor in order to do so. 
I'll try to write something!

**Comment by galatolofederico** [comment]
The solution in e00742c and 58c117c only works for integer ratios but it can be a starting point.
If you run `example.py` it gives you
```
epoch: 0 labels: tensor([1, 2, 2, 0, 1, 2, 2, 0])

epoch: 0 labels: tensor([1, 2, 2, 0, 1, 2, 2, 0])

epoch: 0 labels: tensor([1, 2, 2, 0, 1, 2, 2, 0])

epoch: 0 labels: tensor([1, 2, 2, 0, 1, 2, 2, 0])

epoch: 0 labels: tensor([1, 2, 2, 0, 1, 2, 2, 0])

epoch: 0 labels: tensor([1, 2, 2, 0, 1, 2, 2, 0])
```
with ratios `[1,2,1]`

But it sometimes fails the assertion
```
Traceback (most recent call last):
  File "example.py", line 14, in <module>
    train_loader = torch.utils.data.DataLoader(dataset, sampler=BalancedBatchSampler(dataset, dataset_Y, labels_ratio=[1,2,1]), batch_size=8)
  File "/home/federico/Documents/GitHub/pytorch-balanced-batch/sampler.py", line 35, in __init__
    assert len(self.labels_ratio) == len(self.keys), "You have to specify a ratio for each label"
AssertionError: You have to specify a ratio for each label
```

And the `batch_size` is also dependent on this ratio.

Edit: there is something wrong the class `1` should be the one with high ratio not the class `2` :sweat_smile:

**Comment by mhashas** [comment]
Hi,

That's amazing, it works as I expected thank you! I think the reason why class 2 is getting the high ratio is because the dataset.keys() are populated randomly. This could be solved using: self.dataset = OrderedDict(sorted(self.dataset.items())) assuming an ordering between the keys, which you can also specify.
